export type LatLng = [number, number];

export interface FuelStop {
  id: string;
  name: string;
  brand: string;
  position: LatLng;
  /** Fleet-manager opt-in — only stops explicitly marked trigger a WhatsApp
   * nudge on proximity. Not every fuel stop within range should message the
   * driver; the manager picks which one(s) actually should. */
  notify?: boolean;
}

export interface ServicePoint {
  id: string;
  name: string;
  type: "towing" | "garage";
  phone?: string;
  address?: string;
  position: LatLng;
  /** Set for OSM-sourced (Overpass) results — real but community-maintained data. */
  source?: "osm";
}

/**
 * capacityTotal/available are set for mock TRAVIS-shaped data (see
 * src/lib/travis.ts) but left undefined for real OSM (Overpass) parking
 * results, which don't carry live occupancy — just a real location.
 */
export interface ParkingSpot {
  id: string;
  name: string;
  position: LatLng;
  capacityTotal?: number;
  available?: number;
  address?: string;
  source?: "osm";
}

export type AlertPointKind = "fuel" | "parking";

/**
 * A dispatcher-placed pin, added on the fly (click-on-map) rather than
 * generated by the Locate pipeline — separate from FuelStop/ParkingSpot so
 * "what kind of asset is this" (fuel vs parking) stays independent of "does
 * this trigger a WhatsApp nudge," which every manually-added point does by
 * default since that's the reason it was placed.
 */
export interface AlertPoint {
  id: string;
  name: string;
  kind: AlertPointKind;
  position: LatLng;
  notify: boolean;
}

export type AlertType = "gps_silent" | "near_fuel_stop" | "sos";

export interface TripAlert {
  type: AlertType;
  message: string;
}

export type TruckStatus = "in_transit" | "gps_silent" | "idle";
export type EnrichStatus = "idle" | "loading" | "done" | "error";

/** Default radius (km) for a truck's WhatsApp fuel-stop proximity alert. */
export const DEFAULT_FUEL_PROXIMITY_KM = 15;

/** Language the WhatsApp bot replies in for this driver — per-driver, not fleet-wide. */
export type DriverLanguage = "ro" | "en";
export const DEFAULT_DRIVER_LANGUAGE: DriverLanguage = "ro";

/**
 * One independently switchable WhatsApp trigger. Threshold is km for the
 * three proximity/distance kinds, minutes for gps_silent — each truck turns
 * on only the rules it needs, at its own threshold, instead of one shared
 * switch/radius for every trigger type. gps_silent and route_deviation are
 * also the two triggers meant to escalate to a voice call (see
 * src/lib/whatsappTemplates.ts), not just a WhatsApp text — near_fuel_stop
 * and near_parking stay text-only nudges.
 */
export type AlertRuleKind = "near_fuel_stop" | "near_parking" | "gps_silent" | "route_deviation";

export interface AlertRule {
  enabled: boolean;
  threshold: number;
}

export const DEFAULT_ALERT_THRESHOLD: Record<AlertRuleKind, number> = {
  near_fuel_stop: DEFAULT_FUEL_PROXIMITY_KM,
  near_parking: DEFAULT_FUEL_PROXIMITY_KM,
  gps_silent: 30,
  route_deviation: 10,
};

/** Fresh object each call — these get spread into per-truck state, never shared by reference. */
export function defaultAlertRules(): Record<AlertRuleKind, AlertRule> {
  return {
    near_fuel_stop: { enabled: false, threshold: DEFAULT_ALERT_THRESHOLD.near_fuel_stop },
    near_parking: { enabled: false, threshold: DEFAULT_ALERT_THRESHOLD.near_parking },
    gps_silent: { enabled: false, threshold: DEFAULT_ALERT_THRESHOLD.gps_silent },
    route_deviation: { enabled: false, threshold: DEFAULT_ALERT_THRESHOLD.route_deviation },
  };
}

/**
 * One row = one truck, combining what used to be split across separate
 * Driver/Trip records — matches the shape of an uploaded Excel row plus the
 * fields the app fills in once you hit "Locate" (see src/lib/enrichTruck.ts).
 */
export interface TruckEntry {
  id: string;
  driverName: string;
  phone: string;
  truckType: string;
  truckPlate: string;
  sourceLabel: string;
  destinationLabel: string;
  notes: string;
  status: TruckStatus;
  /** Timestamp (Date.now()) of the last time `status` changed — how long a
   * "GPS silent" truck has actually been silent is measured from this, not
   * from when the page happened to load. Set automatically by the fleet
   * store's reducer whenever `status` changes, never patched directly. */
  statusSince?: number;
  showOnMap: boolean;
  /** Per-truck, fleet-manager controlled — defaults OFF for every rule. No
   * global switch and no single shared radius: each truck turns on exactly
   * the triggers it needs (near a fuel stop, near parking, GPS gone quiet),
   * each at its own threshold, deliberately, after an early version's single
   * fleet-wide switch+radius turned out to be the wrong shape for this. */
  alertRules: Record<AlertRuleKind, AlertRule>;
  /** Language the WhatsApp bot's text replies use for this driver. */
  language: DriverLanguage;
  /** Language a future voice agent would use for this driver — set now, independent of `language`, since a driver's read/write language and spoken language aren't always the same. Not consumed anywhere yet. */
  voiceLanguage: DriverLanguage;
  alert?: TripAlert;
  /** 0-1 starting position along the route, seeds the live-movement simulation. */
  startProgress: number;
  durationMinutes?: number;
  distanceKm?: number;
  /** Real figure, only present for seed trucks with actual DispatchMaster revenue. */
  revenueEur?: number;
  /** Computed estimate for trucks located via the live pipeline — see enrichTruck.ts. */
  estimatedFuelCostEur?: number;

  sourceCoord?: LatLng;
  destCoord?: LatLng;
  /** Route endpoints (2-3 points) fed to fetchTruckRoute — not itself the rendered path. */
  route?: LatLng[];
  fuelStops: FuelStop[];
  serviceStops: ServicePoint[];
  parkingStops: ParkingSpot[];
  /** Dispatcher-added, on the fly — see AlertPoint's doc comment. */
  alertPoints: AlertPoint[];

  enrichStatus: EnrichStatus;
  enrichError?: string;
}

// Real Continent Trans SRL trucks, pulled from DispatchMaster (Flotă +
// Operațiuni > Istoric) — real plates, models, source/destination text, and
// revenue. Driver names/phone numbers are placeholders — see
// seed-data/continent_trans_sample.xlsx. This is the default fleet shown
// until you upload your own — same data path, not a separate system.
//
// Deliberately NOT pre-located: route/fuel/maintenance/parking stay empty
// until you press "Locate," same as any truck you add or upload yourself —
// one consistent rule, not seed trucks behaving differently from new ones.
export const DEFAULT_TRUCKS: TruckEntry[] = [
  {
    id: "seed-1",
    driverName: "Mihai Constantinescu",
    phone: "+40 745 111 222",
    truckType: "Scania (2022)",
    truckPlate: "SV03CFC",
    sourceLabel: "Berlin, DE",
    destinationLabel: "Turin, IT",
    notes: "",
    status: "in_transit",
    showOnMap: true,
    alertRules: defaultAlertRules(),
    language: DEFAULT_DRIVER_LANGUAGE,
    voiceLanguage: DEFAULT_DRIVER_LANGUAGE,
    startProgress: 0.12,
    revenueEur: 2248.25,
    fuelStops: [],
    serviceStops: [],
    parkingStops: [],
    alertPoints: [],
    enrichStatus: "idle",
  },
  {
    id: "seed-2",
    driverName: "Bogdan Ardelean",
    phone: "+40 745 222 333",
    truckType: "Mercedes Benz 1848 (2026)",
    truckPlate: "SV84CFC",
    sourceLabel: "Turin, IT",
    destinationLabel: "Dortmund, DE",
    notes: "",
    status: "in_transit",
    showOnMap: true,
    alertRules: defaultAlertRules(),
    language: DEFAULT_DRIVER_LANGUAGE,
    voiceLanguage: DEFAULT_DRIVER_LANGUAGE,
    startProgress: 0.35,
    revenueEur: 2345.51,
    fuelStops: [],
    serviceStops: [],
    parkingStops: [],
    alertPoints: [],
    enrichStatus: "idle",
  },
  {
    id: "seed-3",
    driverName: "Cristian Moraru",
    phone: "+40 745 333 444",
    truckType: "MAN 480 (2016)",
    truckPlate: "SV19CFC",
    sourceLabel: "Poznań, PL",
    destinationLabel: "Turin, IT",
    notes: "",
    status: "gps_silent",
    showOnMap: true,
    alertRules: defaultAlertRules(),
    language: DEFAULT_DRIVER_LANGUAGE,
    voiceLanguage: DEFAULT_DRIVER_LANGUAGE,
    startProgress: 0.5,
    revenueEur: 4000.0,
    fuelStops: [],
    serviceStops: [],
    parkingStops: [],
    alertPoints: [],
    enrichStatus: "idle",
  },
  {
    id: "seed-4",
    driverName: "Radu Petrescu",
    phone: "+40 745 444 555",
    truckType: "Scania S500 (2018)",
    truckPlate: "SV31CFC",
    sourceLabel: "Hannover, DE",
    destinationLabel: "Hannover, DE (round trip)",
    notes: "",
    status: "idle",
    showOnMap: true,
    alertRules: defaultAlertRules(),
    language: DEFAULT_DRIVER_LANGUAGE,
    voiceLanguage: DEFAULT_DRIVER_LANGUAGE,
    startProgress: 0.02,
    revenueEur: 1991.0,
    fuelStops: [],
    serviceStops: [],
    parkingStops: [],
    alertPoints: [],
    enrichStatus: "idle",
  },
  {
    id: "seed-5",
    driverName: "Alexandru Barbu",
    phone: "+40 745 555 666",
    truckType: "MAN 440 (2013)",
    truckPlate: "SV24CFC",
    sourceLabel: "Dortmund, DE",
    destinationLabel: "Dortmund, DE (round trip)",
    notes: "",
    status: "in_transit",
    showOnMap: true,
    alertRules: defaultAlertRules(),
    language: DEFAULT_DRIVER_LANGUAGE,
    voiceLanguage: DEFAULT_DRIVER_LANGUAGE,
    startProgress: 0.68,
    revenueEur: 5724.2,
    fuelStops: [],
    serviceStops: [],
    parkingStops: [],
    alertPoints: [],
    enrichStatus: "idle",
  },
];
